### ISSUE TITLE
Errors/Unable to compile after updating to V1.1 from V1.0.16

### ISSUE THREAD

**Issue by Cardinen** [newdigate/teensy-variable-playback#67]
Hello, after upgrading the library from V1.0.16 to V1.1 i'm not able to compile anymore with Teensyduino (1.57) and Teensy 4.1. 

There seems to be an error in the file ResamplingReader.h .

This is the error i get: error: array must be initialized with a brace-enclosed initializer    

at this line: ResamplingReader() {
}

ps. Love this library, hope someone help me

Thank you!

**Comment by newdigate** [comment]
Can you give us some context? Is that line in your code or the library? 
The best thing to do is stick on the version that works - it’s unlikely there’s any features in 1.1 that you’ll need

**Comment by Cardinen** [comment]
Ok sorry, I'm not a code expert.
Teensyduino updated my library and since then I have compilation errors in old projects using that library.
I ran the compile error through AI and it suggested that the error is in that line in the file ResamplingReader.h .
He also suggested me to report the error here, that's why I did it.
I've now reverted back to the previous version
